# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_info',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('admin_name', models.CharField(max_length=10, null=True, verbose_name='管理员姓名')),
                ('admin_sex', models.CharField(choices=[('F', '女'), ('M', '男')], max_length=2, null=True, verbose_name='管理员性别')),
                ('admin_age', models.CharField(max_length=3, null=True, verbose_name='管理员年龄')),
                ('admin_ident', models.CharField(max_length=18, null=True, verbose_name='管理员身份证')),
                ('admin_tel', models.CharField(max_length=20, null=True, verbose_name='管理员电话')),
                ('admin_email', models.CharField(max_length=50, null=True, verbose_name='管理员EMAIL')),
                ('admin_type', models.IntegerField(choices=[(0, '大中华地区管理员'), (1, '门店管理员'), (2, '违章处理管理员')], default='门店管理员', verbose_name='管理员类型')),
                ('admin_record_create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('record_delete_status', models.CharField(choices=[('dele', '已删除'), ('no', '正常')], default='正常', max_length=4, verbose_name='删除状态位')),
            ],
            options={
                'verbose_name': '管理员信息',
                'verbose_name_plural': '管理员信息',
            },
        ),
        migrations.CreateModel(
            name='car_info',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('car_num', models.CharField(max_length=10, null=True)),
                ('car_color', models.CharField(choices=[('red', '红色'), ('bla', '黑色'), ('sli', '银色')], default='黑色', max_length=4, verbose_name='颜色')),
                ('car_engine_num', models.CharField(max_length=10, null=True, verbose_name='发动机号')),
                ('car_frame_num', models.CharField(max_length=20, null=True, verbose_name='车架编号')),
                ('car_buy_date', models.CharField(max_length=4, null=True, verbose_name='购车年份')),
                ('car_retailer', models.CharField(max_length=20, null=True, verbose_name='销售商')),
                ('car_status', models.CharField(choices=[('N', '未租'), ('R', '已租'), ('F', '维修')], default='未租', max_length=4, verbose_name='车辆状态')),
                ('car_ins_num', models.CharField(max_length=50, null=True, verbose_name='保单编号')),
                ('car_record_create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('record_delete_status', models.CharField(choices=[('dele', '已删除'), ('no', '正常')], default='正常', max_length=4, verbose_name='删除状态位')),
            ],
            options={
                'verbose_name': '车辆信息',
                'verbose_name_plural': '车辆信息',
            },
        ),
        migrations.CreateModel(
            name='driving_license',
            fields=[
                ('drive_id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('user_drive', models.CharField(max_length=12, null=True, verbose_name='驾驶证编号')),
                ('drive_type', models.CharField(default='C级驾照', max_length=12, verbose_name='驾驶证类型')),
                ('drive_age', models.IntegerField(null=True, verbose_name='驾龄')),
                ('drive_start_date', models.DateField(null=True, verbose_name='发证日期')),
                ('drive_end_date', models.DateField(null=True, verbose_name='失效日期')),
            ],
            options={
                'verbose_name': '驾驶证信息',
                'verbose_name_plural': '驾驶证信息',
            },
        ),
        migrations.CreateModel(
            name='illegal_record',
            fields=[
                ('illegal_id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('illegal_date', models.DateField(null=True, verbose_name='违章时间')),
                ('illegal_bill', models.IntegerField(null=True, verbose_name='违章金额/元')),
                ('illegal_info', models.TextField(null=True, verbose_name='违章信息')),
                ('illegal_record_create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('record_delete_status', models.CharField(choices=[('dele', '已删除'), ('no', '正常')], default='正常', max_length=4, verbose_name='删除状态位')),
                ('illegal_car_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illegal_car', to='RentMe.car_info', verbose_name='违章车辆车牌')),
            ],
            options={
                'verbose_name': '违章记录',
                'verbose_name_plural': '违章记录',
            },
        ),
        migrations.CreateModel(
            name='model_info',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('car_model_id', models.CharField(max_length=40, verbose_name='品牌/车系/年代款/配置款')),
                ('car_type', models.IntegerField(choices=[(0, 'SUV'), (1, '商务车')], null=True, verbose_name='车型')),
                ('car_brand', models.CharField(default='奔驰', max_length=20, verbose_name='品牌')),
                ('car_series', models.CharField(default='X3', max_length=20, verbose_name='车系')),
                ('car_issue_date', models.CharField(default='2017', max_length=6, verbose_name='年代')),
                ('car_config_model', models.CharField(default='悦动型', max_length=10, verbose_name='配置款')),
                ('car_seats_num', models.IntegerField(null=True, verbose_name='座位数')),
                ('car_doors', models.IntegerField(null=True, verbose_name='车门数')),
                ('car_fuel_type', models.CharField(max_length=5, null=True, verbose_name='燃料类型')),
                ('car_gearbox_type', models.CharField(max_length=5, null=True, verbose_name='变速箱类型')),
                ('car_displacement', models.CharField(max_length=5, null=True, verbose_name='排量')),
                ('car_fuel_num', models.CharField(max_length=10, null=True, verbose_name='使用燃油编号')),
                ('car_drive_way', models.CharField(max_length=5, null=True, verbose_name='驱动方式')),
                ('car_engine_intake', models.CharField(max_length=10, null=True, verbose_name='发动机进气方式')),
                ('car_skylight', models.CharField(choices=[('Sing', '单天窗'), ('all', '全景天窗'), ('else', '其他'), ('N', '无')], default='无', max_length=5, verbose_name='天窗')),
                ('car_tank_capa', models.IntegerField(null=True, verbose_name='邮箱容量')),
                ('car_voicebox', models.CharField(max_length=2, null=True, verbose_name='音箱')),
                ('car_seats_type', models.CharField(max_length=10, null=True, verbose_name='座椅')),
                ('car_reverse_radar', models.CharField(choices=[('Y', '有'), ('N', '无')], default='无', max_length=4, verbose_name='倒车雷达')),
                ('car_airbag', models.CharField(max_length=2, null=True, verbose_name='气囊')),
                ('car_dvd', models.CharField(choices=[('D', 'DVD'), ('C', 'CD'), ('S', '其他')], default='DVD', max_length=4, verbose_name='影音配置')),
                ('car_gps', models.CharField(choices=[('Y', '有'), ('N', '无')], default='无', max_length=5, verbose_name='GPS导航')),
                ('car_deposit', models.IntegerField(default=5000, verbose_name='押金')),
                ('car_day_price', models.IntegerField(default=1000, verbose_name='日租金')),
                ('car_time_out_price', models.IntegerField(default=150, verbose_name='超时费用(元/天)')),
                ('car_over_kilo_price', models.FloatField(default=0.5, verbose_name='超公里费用(元/公里)')),
                ('car_record_create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('record_delete_status', models.CharField(choices=[('dele', '已删除'), ('no', '正常')], default='正常', max_length=4, verbose_name='删除状态位')),
            ],
            options={
                'verbose_name': '车型',
                'verbose_name_plural': '车型',
            },
        ),
        migrations.CreateModel(
            name='relet_record',
            fields=[
                ('relet_id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('relet_day', models.IntegerField(null=True, verbose_name='续租天数')),
                ('relet_record_create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('record_delete_status', models.CharField(choices=[('dele', '已删除'), ('no', '正常')], default='正常', max_length=4, verbose_name='删除状态位')),
            ],
            options={
                'verbose_name': '续租信息',
                'verbose_name_plural': '续租信息',
            },
        ),
        migrations.CreateModel(
            name='rent_order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('pick_time', models.DateTimeField(null=True, verbose_name='取车时间')),
                ('drop_time', models.DateTimeField(null=True, verbose_name='还车时间')),
                ('actual_deposit', models.IntegerField(null=True, verbose_name='实收押金')),
                ('breaken_bill', models.IntegerField(null=True, verbose_name='维修费用')),
                ('illegal_info', models.TextField(null=True, verbose_name='违章信息')),
                ('illegal_bill', models.IntegerField(null=True, verbose_name='违章费用')),
                ('actual_money', models.IntegerField(null=True, verbose_name='实收总费用')),
                ('order_record_create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('record_delete_status', models.CharField(choices=[('dele', '已删除'), ('no', '正常')], default='正常', max_length=4, verbose_name='删除状态位')),
                ('car_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_car', to='RentMe.car_info', verbose_name='车牌')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
            },
        ),
        migrations.CreateModel(
            name='store_info',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('store_addr', models.CharField(max_length=50, null=True, verbose_name='门店地址')),
                ('store_tel', models.CharField(max_length=20, null=True, verbose_name='门店联系方式')),
                ('store_start_time', models.CharField(max_length=20, null=True, verbose_name='门店营业时间')),
                ('store_record_create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('record_delete_status', models.CharField(choices=[('dele', '已删除'), ('no', '正常')], default='正常', max_length=4, verbose_name='删除状态位')),
                ('store_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_manage', to='RentMe.admin_info', verbose_name='门店管理员')),
            ],
            options={
                'verbose_name': '门店信息',
                'verbose_name_plural': '门店信息',
            },
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('user_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('user_sex', models.CharField(choices=[('F', '女'), ('M', '男')], max_length=2, verbose_name='性别')),
                ('user_age', models.CharField(max_length=3, null=True, verbose_name='年龄')),
                ('user_ident', models.CharField(max_length=18, null=True, verbose_name='身份证号')),
                ('user_tel', models.CharField(max_length=15, null=True, verbose_name='电话')),
                ('user_office', models.CharField(max_length=50, null=True, verbose_name='工作单位')),
                ('user_addr', models.CharField(max_length=50, null=True, verbose_name='地址')),
                ('user_post', models.CharField(max_length=6, null=True, verbose_name='邮编')),
                ('user_email', models.CharField(max_length=50, null=True, verbose_name='EMAIL')),
                ('user_record_create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('record_delete_status', models.CharField(choices=[('dele', '已删除'), ('no', '正常')], default='正常', max_length=4, verbose_name='删除状态位')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.AddField(
            model_name='rent_order',
            name='pick_addr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_store', to='RentMe.store_info', verbose_name='取车门店'),
        ),
        migrations.AddField(
            model_name='rent_order',
            name='user_drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_driver', to='RentMe.driving_license', verbose_name='驾驶人驾驶信息'),
        ),
        migrations.AddField(
            model_name='rent_order',
            name='user_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rent', to='RentMe.user_info', verbose_name='租车用户'),
        ),
        migrations.AddField(
            model_name='relet_record',
            name='order_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relet_order', to='RentMe.rent_order'),
        ),
        migrations.AddField(
            model_name='car_info',
            name='car_model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_model', to='RentMe.model_info'),
        ),
    ]
