# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_info',
            fields=[
                ('admin_num', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=10, null=True, verbose_name='管理员姓名')),
                ('admin_sex', models.CharField(choices=[('F', '女'), ('M', '男')], max_length=2, null=True, verbose_name='管理员性别')),
                ('admin_age', models.CharField(max_length=3, null=True, verbose_name='管理员年龄')),
                ('admin_ident', models.CharField(max_length=18, null=True, verbose_name='管理员身份证')),
                ('admin_tel', models.CharField(max_length=20, null=True, verbose_name='管理员电话')),
                ('admin_email', models.CharField(max_length=50, null=True, verbose_name='管理员EMAIL')),
                ('admin_type', models.IntegerField(choices=[(0, '大中华地区管理员'), (1, '门店管理员'), (2, '违章处理管理员')], default='门店管理员', verbose_name='管理员类型')),
            ],
        ),
        migrations.CreateModel(
            name='car_info',
            fields=[
                ('car_num', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('car_color', models.CharField(choices=[('red', '红色'), ('bla', '黑色'), ('sli', '银色')], default='黑色', max_length=4, verbose_name='颜色')),
                ('car_engine_num', models.CharField(max_length=10, null=True, verbose_name='发动机号')),
                ('car_frame_num', models.CharField(max_length=20, null=True, verbose_name='车架编号')),
                ('car_buy_date', models.CharField(max_length=4, null=True, verbose_name='购车年份')),
                ('car_retailer', models.CharField(max_length=20, null=True, verbose_name='销售商')),
                ('car_status', models.CharField(choices=[('N', '未租'), ('R', '已租'), ('F', '维修')], default='未租', max_length=4, verbose_name='车辆状态')),
                ('car_ins_num', models.CharField(max_length=50, null=True, verbose_name='保单编号')),
            ],
        ),
        migrations.CreateModel(
            name='model_info',
            fields=[
                ('car_model_id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='品牌/车系/年代款/配置款')),
                ('car_type', models.IntegerField(choices=[(0, 'SUV'), (1, '商务车')], verbose_name='车型')),
                ('car_brand', models.CharField(default='奔驰', max_length=20)),
                ('car_series', models.CharField(default='X3', max_length=20)),
                ('car_issue_date', models.CharField(default='2017', max_length=4)),
                ('car_config_model', models.CharField(default='悦动型', max_length=10)),
                ('car_seats_num', models.IntegerField(null=True)),
                ('car_doors', models.IntegerField(null=True)),
                ('car_flues_types', models.CharField(max_length=5, null=True, verbose_name='燃料类型')),
                ('car_gearbox_type', models.CharField(max_length=5, null=True, verbose_name='变速箱类型')),
                ('car_displacement', models.IntegerField(null=True, verbose_name='排量')),
                ('car_fuel_num', models.CharField(max_length=10, null=True, verbose_name='使用燃油编号')),
                ('car_drive_way', models.CharField(max_length=5, null=True, verbose_name='驱动方式')),
                ('car_engine_intake', models.CharField(max_length=10, null=True, verbose_name='发动机进气方式')),
                ('car_skylight', models.CharField(choices=[('Y', '有'), ('N', '无')], default='无', max_length=5, verbose_name='天窗')),
                ('car_tank_capa', models.IntegerField(null=True, verbose_name='邮箱容量')),
                ('car_voicebox', models.IntegerField(null=True, verbose_name='音箱')),
                ('car_seats_type', models.CharField(max_length=10, null=True, verbose_name='座椅')),
                ('car_reverse_radar', models.CharField(choices=[('Y', '有'), ('N', '无')], default='无', max_length=4, verbose_name='倒车雷达')),
                ('car_airbag', models.IntegerField(null=True, verbose_name='气囊')),
                ('car_dvd', models.CharField(choices=[('D', 'DVD'), ('C', 'VCD')], default='DVD', max_length=4)),
                ('car_gps', models.CharField(choices=[('Y', '有'), ('N', '无')], default='无', max_length=5, verbose_name='GPS导航')),
                ('car_deposit', models.IntegerField(default=5000, verbose_name='押金')),
                ('car_day_price', models.IntegerField(default=1000, verbose_name='日租金')),
                ('car_time_out_price', models.IntegerField(default=150, verbose_name='超时费用(元/天)')),
                ('car_over_kilo_price', models.FloatField(default=0.5, verbose_name='超公里费用(元/公里)')),
            ],
        ),
        migrations.CreateModel(
            name='relet_record',
            fields=[
                ('relet_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('relet_day', models.IntegerField()),
                ('relet_apply_day', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='rent_order',
            fields=[
                ('order_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pick_addr', models.CharField(max_length=50)),
                ('car_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_car', to='RentMe.car_info')),
            ],
        ),
        migrations.CreateModel(
            name='store_info',
            fields=[
                ('store_num', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('store_addr', models.CharField(max_length=50, null=True, verbose_name='门店地址')),
                ('store_tel', models.CharField(max_length=20, null=True, verbose_name='门店联系方式')),
                ('store_start_time', models.CharField(max_length=20, null=True, verbose_name='门店营业时间')),
                ('store_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_manage', to='RentMe.admin_info', verbose_name='门店管理员')),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('user_num', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=10)),
                ('user_sex', models.CharField(choices=[('F', '女'), ('M', '男')], max_length=2, verbose_name='性别')),
                ('user_age', models.CharField(max_length=3, null=True, verbose_name='年龄')),
                ('user_ident', models.CharField(max_length=18, null=True, verbose_name='身份证号')),
                ('user_tel', models.CharField(max_length=15, null=True, verbose_name='电话')),
                ('user_office', models.CharField(max_length=50, null=True, verbose_name='工作单位')),
                ('user_addr', models.CharField(max_length=50, null=True, verbose_name='地址')),
                ('user_post', models.CharField(max_length=6, null=True, verbose_name='邮编')),
                ('user_email', models.CharField(max_length=50, null=True, verbose_name='EMAIL')),
            ],
        ),
        migrations.AddField(
            model_name='rent_order',
            name='store_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_atstore', to='RentMe.store_info'),
        ),
        migrations.AddField(
            model_name='rent_order',
            name='user_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rent', to='RentMe.user_info'),
        ),
        migrations.AddField(
            model_name='relet_record',
            name='order_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relet_order', to='RentMe.rent_order'),
        ),
        migrations.AddField(
            model_name='car_info',
            name='car_model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_model', to='RentMe.model_info'),
        ),
    ]
