# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentMe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driving_license',
            name='license_record_create_time',
        ),
        migrations.RemoveField(
            model_name='driving_license',
            name='record_create_admin',
        ),
    ]
