# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentMe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_info',
            name='admin_pas',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
