# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentMe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='driving_license',
            fields=[
                ('drive_id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('user_drive', models.CharField(max_length=12, null=True, verbose_name='驾驶证编号')),
                ('drive_type', models.CharField(max_length=3, null=True, verbose_name='驾驶证类型')),
                ('drive_age', models.IntegerField(null=True, verbose_name='驾龄')),
                ('drive_start_date', models.DateField(null=True, verbose_name='发证日期')),
                ('drive_end_date', models.DateField(null=True, verbose_name='失效日期')),
            ],
        ),
        migrations.RemoveField(
            model_name='rent_order',
            name='initial_drop_time',
        ),
        migrations.RemoveField(
            model_name='rent_order',
            name='relet_day',
        ),
        migrations.AddField(
            model_name='rent_order',
            name='actual_deposit',
            field=models.IntegerField(null=True, verbose_name='实收押金'),
        ),
        migrations.AddField(
            model_name='rent_order',
            name='actual_money',
            field=models.IntegerField(null=True, verbose_name='实收总费用'),
        ),
        migrations.AddField(
            model_name='rent_order',
            name='drop_time',
            field=models.DateTimeField(null=True, verbose_name='还车时间'),
        ),
        migrations.AlterField(
            model_name='rent_order',
            name='pick_time',
            field=models.DateTimeField(null=True, verbose_name='取车时间'),
        ),
        migrations.AlterField(
            model_name='rent_order',
            name='user_drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_driver', to='RentMe.driving_license', verbose_name='驾驶人驾驶信息'),
        ),
    ]
