# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentMe', '0002_auto_20170621_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='illegal_record',
            fields=[
                ('illegal_id', models.AutoField(primary_key=True, serialize=False)),
                ('illegal_date', models.DateField(null=True, verbose_name='违章时间')),
                ('illegal_bill', models.IntegerField(null=True, verbose_name='违章金额/元')),
                ('illegal_info', models.TextField(null=True, verbose_name='违章信息')),
                ('illegal_car_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illegal_car', to='RentMe.car_info', verbose_name='违章车辆车牌')),
            ],
        ),
        migrations.RemoveField(
            model_name='rent_order',
            name='drop_time',
        ),
        migrations.AddField(
            model_name='rent_order',
            name='breaken_bill',
            field=models.IntegerField(null=True, verbose_name='维修费用'),
        ),
        migrations.AddField(
            model_name='rent_order',
            name='illegal_bill',
            field=models.IntegerField(null=True, verbose_name='违章费用'),
        ),
        migrations.AddField(
            model_name='rent_order',
            name='illegal_info',
            field=models.TextField(null=True, verbose_name='违章信息'),
        ),
        migrations.AddField(
            model_name='rent_order',
            name='initial_drop_time',
            field=models.DateField(null=True, verbose_name='还车时间'),
        ),
        migrations.AddField(
            model_name='rent_order',
            name='relet_day',
            field=models.IntegerField(default=0, verbose_name='续租天数'),
        ),
        migrations.AlterField(
            model_name='relet_record',
            name='relet_day',
            field=models.IntegerField(null=True, verbose_name='续租天数'),
        ),
        migrations.AlterField(
            model_name='rent_order',
            name='car_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_car', to='RentMe.car_info', verbose_name='车牌'),
        ),
        migrations.AlterField(
            model_name='rent_order',
            name='pick_time',
            field=models.DateField(null=True, verbose_name='取车时间'),
        ),
        migrations.AlterField(
            model_name='rent_order',
            name='user_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rent', to='RentMe.user_info', verbose_name='租车用户'),
        ),
    ]
