# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentMe', '0002_auto_20170622_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driving_license',
            options={'verbose_name': '驾驶证信息', 'verbose_name_plural': '驾驶证信息'},
        ),
    ]
