# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentMe', '0003_auto_20170621_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin_info',
            options={'verbose_name': '管理员信息', 'verbose_name_plural': '管理员信息'},
        ),
        migrations.AlterModelOptions(
            name='car_info',
            options={'verbose_name': '车辆信息', 'verbose_name_plural': '车辆信息'},
        ),
        migrations.AlterModelOptions(
            name='illegal_record',
            options={'verbose_name': '违章记录', 'verbose_name_plural': '违章记录'},
        ),
        migrations.AlterModelOptions(
            name='model_info',
            options={'verbose_name': '车型', 'verbose_name_plural': '车型'},
        ),
        migrations.AlterModelOptions(
            name='relet_record',
            options={'verbose_name': '续租信息', 'verbose_name_plural': '续租信息'},
        ),
        migrations.AlterModelOptions(
            name='rent_order',
            options={'verbose_name': '订单信息', 'verbose_name_plural': '订单信息'},
        ),
        migrations.AlterModelOptions(
            name='store_info',
            options={'verbose_name': '门店信息', 'verbose_name_plural': '门店信息'},
        ),
        migrations.AlterModelOptions(
            name='user_info',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.RenameField(
            model_name='model_info',
            old_name='car_flues_types',
            new_name='car_flue_type',
        ),
    ]
