# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentMe', '0003_auto_20170623_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_info',
            name='car_config_model',
            field=models.CharField(default='悦动型', max_length=10, verbose_name='配置款'),
        ),
        migrations.AlterField(
            model_name='model_info',
            name='car_doors',
            field=models.IntegerField(null=True, verbose_name='车门数'),
        ),
        migrations.AlterField(
            model_name='model_info',
            name='car_dvd',
            field=models.CharField(choices=[('D', 'DVD'), ('C', 'CD'), ('S', '其他')], default='DVD', max_length=4, verbose_name='影音配置'),
        ),
        migrations.AlterField(
            model_name='model_info',
            name='car_gps',
            field=models.CharField(choices=[('Y', '有'), ('N', '无')], default='无', max_length=5, verbose_name='GPS导航'),
        ),
        migrations.AlterField(
            model_name='model_info',
            name='car_reverse_radar',
            field=models.CharField(choices=[('Y', '有'), ('N', '无')], default='无', max_length=4, verbose_name='倒车雷达'),
        ),
        migrations.AlterField(
            model_name='model_info',
            name='car_seats_num',
            field=models.IntegerField(null=True, verbose_name='座位数'),
        ),
        migrations.AlterField(
            model_name='model_info',
            name='car_series',
            field=models.CharField(default='X3', max_length=20, verbose_name='车系'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_name',
            field=models.CharField(max_length=10, verbose_name='姓名'),
        ),
    ]
