# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentMe', '0005_auto_20170622_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_info',
            name='car_type',
            field=models.IntegerField(choices=[(0, 'SUV'), (1, '商务车')], null=True, verbose_name='车型'),
        ),
    ]
