# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentMe', '0006_auto_20170622_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_info',
            name='car_dvd',
            field=models.CharField(choices=[('D', 'DVD'), ('C', 'CD'), ('S', '其他')], default='DVD', max_length=4),
        ),
        migrations.AlterField(
            model_name='model_info',
            name='car_gps',
            field=models.CharField(choices=[('Sing', '单天窗'), ('all', '全景天窗'), ('else', '其他'), ('N', '无')], default='无', max_length=5, verbose_name='GPS导航'),
        ),
        migrations.AlterField(
            model_name='model_info',
            name='car_reverse_radar',
            field=models.CharField(choices=[('Sing', '单天窗'), ('all', '全景天窗'), ('else', '其他'), ('N', '无')], default='无', max_length=4, verbose_name='倒车雷达'),
        ),
        migrations.AlterField(
            model_name='model_info',
            name='car_skylight',
            field=models.CharField(choices=[('Sing', '单天窗'), ('all', '全景天窗'), ('else', '其他'), ('N', '无')], default='无', max_length=5, verbose_name='天窗'),
        ),
    ]
