# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentMe', '0007_auto_20170622_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_info',
            name='car_airbag',
            field=models.CharField(max_length=4, null=True, verbose_name='气囊'),
        ),
    ]
